allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@astrojs/mdx@6.0.3 || 7.0.2'
  - astro@6.4.5 || 7.0.6
  - '@astrojs/internal-helpers@0.10.1'
  - '@astrojs/markdown-remark@7.2.1'
  - '@astrojs/markdown-satteri@0.3.3'
