allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@astrojs/mdx@6.0.3 || 7.0.2'
  - astro@6.4.5 || 7.0.6
  - '@astrojs/internal-helpers@0.10.1'
  - '@astrojs/markdown-remark@7.2.1'
  - '@astrojs/markdown-satteri@0.3.3'
overrides:
  '@xmldom/xmldom@>=0.9.0 <0.9.10': ^0.9.12
  '@xmldom/xmldom@>=0.9.0 <=0.9.10': ^0.9.12
  '@xmldom/xmldom@>=0.9.0 <=0.9.11': ^0.9.12
  '@xmldom/xmldom@>=0.9.0-beta.1 <=0.9.11': ^0.9.12
  '@xmldom/xmldom@>=0.9.0-beta.9 <=0.9.10': ^0.9.12
  devalue@<5.9.1: ^5.9.1
  fast-xml-builder@<=1.1.6: ^1.1.7
  fast-xml-parser@<5.7.0: ^5.7.0
  nanoid@<3.3.16: ^3.3.16
  nanoid@<3.3.18: ^3.3.18
  postcss@<=8.5.17: ^8.5.18
  postcss@<=8.5.22: ^8.5.23
  smol-toml@<=1.7.0: ^1.7.1
  uuid@<11.1.1: ^11.1.1
